apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: frontend
  namespace: onlineboutique
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - onlineboutique
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - frontend
          - frontend-primary
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 15s
