apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: frontend
  namespace: onlineboutique
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - onlineboutique
  selector:
    matchLabels:
      app: frontend
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 15s
