{{- if .Values.serviceMeshIstio.create }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - {{ .Values.frontend.name }}
          # Flagger suffixes the primary deployment label (e.g. frontend -> frontend-primary).
          - {{ printf "%s-primary" .Values.frontend.name }}
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 15s
{{- end }}
