apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: onlineboutique
  namespace: argocd
spec:
  description: Online Boutique microservices
  sourceRepos:
  - '*'
  destinations:
  - namespace: onlineboutique
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
