apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: frontend-request-success-rate
  namespace: onlineboutique
spec:
  provider:
    type: prometheus
    address: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
  query: |
    (
      sum(
        rate(
          istio_requests_total{
            reporter="source",
            source_workload="istio-ingressgateway",
            source_workload_namespace="istio-system",
            destination_workload_namespace="{{ namespace }}",
            destination_canonical_service="{{ name }}",
            destination_workload=~"{{ name }}(-primary|-canary)?",
            request_protocol="http",
            response_code!~"5.*"
          }[{{ interval }}]
        )
      )
      /
      sum(
        rate(
          istio_requests_total{
            reporter="source",
            source_workload="istio-ingressgateway",
            source_workload_namespace="istio-system",
            destination_workload_namespace="{{ namespace }}",
            destination_canonical_service="{{ name }}",
            destination_workload=~"{{ name }}(-primary|-canary)?",
            request_protocol="http"
          }[{{ interval }}]
        )
      )
    ) * 100
---
apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: frontend-request-duration
  namespace: onlineboutique
spec:
  provider:
    type: prometheus
    address: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
  query: |
    histogram_quantile(
      0.99,
      sum(
        rate(
          istio_request_duration_milliseconds_bucket{
            reporter="source",
            source_workload="istio-ingressgateway",
            source_workload_namespace="istio-system",
            destination_workload_namespace="{{ namespace }}",
            destination_canonical_service="{{ name }}",
            destination_workload=~"{{ name }}(-primary|-canary)?",
            request_protocol="http"
          }[{{ interval }}]
        )
      ) by (le)
    )
