apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onlineboutique-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ragingsnake/microservices-standalone
    targetRevision: main
    path: helm-chart
    helm:
      releaseName: onlineboutique
      parameters:
        - name: images.repository
          value: docker.io/ragingsnake
        - name: images.tag
          value: latest
        - name: frontend.image.tag
          value: v2-good
        - name: frontend.externalService
          value: "false"
        - name: frontend.virtualService.create
          value: "false"
        - name: frontend.virtualService.gateway.name
          value: frontend-gateway
        - name: frontend.virtualService.gateway.namespace
          value: onlineboutique
        - name: frontend.virtualService.hosts[0]
          value: "*"
  destination:
    server: https://kubernetes.default.svc
    namespace: onlineboutique
  ignoreDifferences:
    - group: ""
      kind: Service
      name: frontend
      namespace: onlineboutique
      jsonPointers:
        - /spec/selector
        - /spec/ports/0/targetPort
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
